# Generated by Django 4.2.7 on 2023-12-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='', verbose_name='photo:')),
                ('aty', models.CharField(max_length=50, verbose_name='aty:')),
                ('qurami', models.CharField(max_length=255, verbose_name='qurami:')),
                ('baga', models.CharField(max_length=50, verbose_name='baga:')),
            ],
        ),
    ]
