# Generated by Django 4.2.7 on 2023-12-13 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='product/', verbose_name='photo:')),
                ('aty', models.CharField(max_length=50, verbose_name='aty:')),
                ('qurami', models.TextField(verbose_name='qurami:')),
                ('baga', models.CharField(max_length=50, verbose_name='baga:')),
                ('avi', models.BooleanField()),
                ('group', models.CharField(choices=[('tort', 'tort'), ('pirog', 'pirog'), ('peshenie', 'peshenie'), ('keks', 'keks')], default='tort', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Tort',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.product'),
        ),
    ]
