# Generated by Django 4.2.7 on 2023-12-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_product_remove_cartitem_product_delete_tort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('keks', 'keks'), ('tort', 'tort'), ('pirog', 'pirog')], default='tort', max_length=20),
        ),
    ]
