# Generated by Django 4.2.7 on 2023-12-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_product_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_pro',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('tort', 'tort'), ('keks', 'keks'), ('pirog', 'pirog')], default='tort', max_length=20),
        ),
    ]
