# Generated by Django 4.2.7 on 2023-12-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_cart_pro_cartitem_product_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('keks', 'keks'), ('pirog', 'pirog'), ('tort', 'tort')], default='tort', max_length=20),
        ),
    ]
