# Generated by Django 4.2.7 on 2023-12-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('tort', 'tort'), ('keks', 'keks'), ('pirog', 'pirog')], default='tort', max_length=20),
        ),
    ]
