# Generated by Django 4.2.7 on 2023-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_customer_order_orderitem_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baga',
            field=models.FloatField(max_length=50, verbose_name='baga:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('tort', 'tort'), ('pirog', 'pirog'), ('keks', 'keks')], default='tort', max_length=20),
        ),
    ]
